#!/bin/bash

# Get the C file name from the $CFILE environment variable
c_file="$CFILE"

# Generate the output file name with the .s extension
output_file="${c_file%.c}.s"

# Run the C file through the compiler to generate assembly code
gcc -S -masm=intel "$c_file" -o "$output_file"

